import Erdos.Problem1144.HarperCandidateCovariancePerronKernel
import Mathlib.MeasureTheory.Integral.Pi
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds

open MeasureTheory Finset
open scoped BigOperators

namespace Erdos.Problem1144
noncomputable section

private theorem phase_add (x y : ℝ) :
    candidateCovariancePhase (x + y) =
      candidateCovariancePhase x * candidateCovariancePhase y := by
  simp [candidateCovariancePhase, add_mul, Complex.exp_add]

private theorem phase_conj (x : ℝ) :
    starRingEnd ℂ (candidateCovariancePhase x) = candidateCovariancePhase (-x) := by
  rw [candidateCovariancePhase, ← Complex.exp_conj]
  simp [candidateCovariancePhase]

private theorem phase_norm (x : ℝ) : ‖candidateCovariancePhase x‖ = 1 :=
  Complex.norm_exp_ofReal_mul_I x

private theorem phase_sum {ι : Type*} (s : Finset ι) (x : ι → ℝ) :
    candidateCovariancePhase (∑ i ∈ s, x i) = ∏ i ∈ s, candidateCovariancePhase (x i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [candidateCovariancePhase]
  | @insert a s ha ih => simp [ha, phase_add, ih]

/-- The two independent sets of `k` integration variables in an even Fourier
power. All coordinates carry the original, possibly restricted, measure. -/
def candidateRowPowerMeasure {X : Type*} [MeasurableSpace X] (ν : Measure X) (k : ℕ) :
    Measure ((Fin k → X) × (Fin k → X)) :=
  (Measure.pi fun _ : Fin k => ν).prod (Measure.pi fun _ : Fin k => ν)

/-- The signed sum whose near-integral values survive the discrete average. -/
def candidateRowPowerFrequency {X : Type*} {k : ℕ} (b : X → ℝ)
    (z : (Fin k → X) × (Fin k → X)) : ℝ :=
  (∑ i, b (z.1 i)) - ∑ i, b (z.2 i)

/-- The literal product of Fourier amplitudes in the even-power expansion. -/
def candidateRowPowerAmplitude {X : Type*} {k : ℕ} (f : X → ℂ)
    (z : (Fin k → X) × (Fin k → X)) : ℂ :=
  (∏ i, f (z.1 i)) * starRingEnd ℂ (∏ i, f (z.2 i))

/-- The exact finite geometric sum generated by an equally spaced grid. -/
def candidateRowFourierSum (n : ℕ) (h x : ℝ) : ℂ :=
  ∑ j ∈ range n, candidateCovariancePhase ((j : ℝ) * h * x)

private theorem amplitude_phase {X : Type*} {k : ℕ} (f : X → ℂ) (b : X → ℝ)
    (u : ℝ) (z : (Fin k → X) × (Fin k → X)) :
    candidateRowPowerAmplitude (fun x => f x * candidateCovariancePhase (u * b x)) z =
      candidateRowPowerAmplitude f z * candidateCovariancePhase (u * candidateRowPowerFrequency b z) := by
  unfold candidateRowPowerAmplitude candidateRowPowerFrequency
  simp only [Finset.prod_mul_distrib, map_mul]
  rw [← phase_sum, ← phase_sum, phase_conj]
  rw [← Finset.mul_sum, ← Finset.mul_sum]
  have hp : candidateCovariancePhase (u * ∑ i, b (z.1 i)) *
      candidateCovariancePhase (-(u * ∑ i, b (z.2 i))) =
      candidateCovariancePhase (u * ((∑ i, b (z.1 i)) - ∑ i, b (z.2 i))) := by
    rw [← phase_add]
    congr 1
    ring
  calc
    _ = ((∏ i, f (z.1 i)) * starRingEnd ℂ (∏ i, f (z.2 i))) *
      (candidateCovariancePhase (u * ∑ i, b (z.1 i)) *
        candidateCovariancePhase (-(u * ∑ i, b (z.2 i)))) := by ring
    _ = _ := by rw [hp]

/-- Exact even-power Fourier expansion, with all `2k` variables retained.
This is a finite-product Fubini identity, not a moment assumption. -/
theorem candidate_fourier_even_power_eq {X : Type*} [MeasurableSpace X]
    (ν : Measure X) [SigmaFinite ν] (f : X → ℂ) (b : X → ℝ) (u : ℝ) (k : ℕ) :
    ((‖∫ x, f x * candidateCovariancePhase (u * b x) ∂ν‖ ^ (2 * k) : ℝ) : ℂ) =
      ∫ z, candidateRowPowerAmplitude f z *
        candidateCovariancePhase (u * candidateRowPowerFrequency b z)
        ∂candidateRowPowerMeasure ν k := by
  let g := fun x => f x * candidateCovariancePhase (u * b x)
  have hp := integral_fintype_prod_eq_pow (ι := Fin k) (μ := ν) g
  simp only [Fintype.card_fin] at hp
  have he : ((‖∫ x, g x ∂ν‖ ^ (2 * k) : ℝ) : ℂ) =
      (∫ x, g x ∂ν) ^ k * starRingEnd ℂ ((∫ x, g x ∂ν) ^ k) := by
    rw [Complex.mul_conj, Complex.normSq_eq_norm_sq, norm_pow, ← pow_mul]
    congr 2
    omega
  calc
    _ = (∫ x : Fin k → X, ∏ i, g (x i) ∂Measure.pi (fun _ => ν)) *
        starRingEnd ℂ (∫ x : Fin k → X, ∏ i, g (x i) ∂Measure.pi (fun _ => ν)) := by
      exact he.trans (congrArg₂ (fun a b : ℂ => a * starRingEnd ℂ b) hp.symm hp.symm)
    _ = ∫ z, candidateRowPowerAmplitude g z ∂candidateRowPowerMeasure ν k := by
      unfold candidateRowPowerAmplitude candidateRowPowerMeasure
      calc
        _ = (∫ x : Fin k → X, ∏ i, g (x i) ∂Measure.pi (fun _ => ν)) *
            (∫ x : Fin k → X, starRingEnd ℂ (∏ i, g (x i)) ∂Measure.pi (fun _ => ν)) := by
          congr 1
          exact integral_conj.symm
        _ = _ := (integral_prod_mul _ _).symm
    _ = _ := integral_congr_ae (ae_of_all _ (amplitude_phase f b u))

private theorem amplitude_integrable {X : Type*} [MeasurableSpace X]
    {ν : Measure X} [SigmaFinite ν] {f : X → ℂ} (hf : Integrable f ν) (k : ℕ) :
    Integrable (candidateRowPowerAmplitude f) (candidateRowPowerMeasure ν k) := by
  have hp : Integrable (fun x : Fin k → X => ∏ i, f (x i)) (Measure.pi fun _ => ν) :=
    Integrable.fintype_prod (fun _ => hf)
  exact hp.mul_prod (Complex.conjCLE.toContinuousLinearMap.integrable_comp hp)

private theorem amplitude_phase_integrable {X : Type*} [MeasurableSpace X]
    {ν : Measure X} [SigmaFinite ν] {f : X → ℂ} (hfm : Measurable f)
    (hf : Integrable f ν) {b : X → ℝ} (hb : Measurable b) (k : ℕ) (u : ℝ) :
    Integrable (fun z => candidateRowPowerAmplitude f z *
      candidateCovariancePhase (u * candidateRowPowerFrequency b z)) (candidateRowPowerMeasure ν k) := by
  apply (amplitude_integrable hf k).norm.mono'
  · apply Measurable.aestronglyMeasurable
    unfold candidateRowPowerAmplitude candidateCovariancePhase candidateRowPowerFrequency
    fun_prop
  · exact ae_of_all _ fun z => by rw [norm_mul, phase_norm, mul_one]

/-- Summing the actual powers over an affine grid produces precisely the
geometric-sum resonance factor. The initial grid shift has unit modulus. -/
theorem candidate_fourier_row_power_sum_eq {X : Type*} [MeasurableSpace X]
    (ν : Measure X) [SigmaFinite ν] {f : X → ℂ} (hfm : Measurable f)
    (hf : Integrable f ν) {b : X → ℝ} (hb : Measurable b)
    (u h : ℝ) (n k : ℕ) :
    ((∑ j ∈ range n, ‖∫ x, f x * candidateCovariancePhase ((u + j * h) * b x) ∂ν‖ ^ (2 * k) : ℝ) : ℂ) =
      ∫ z, candidateRowPowerAmplitude f z *
        candidateCovariancePhase (u * candidateRowPowerFrequency b z) *
        candidateRowFourierSum n h (candidateRowPowerFrequency b z)
        ∂candidateRowPowerMeasure ν k := by
  simp only [Complex.ofReal_sum]
  simp_rw [candidate_fourier_even_power_eq ν f b _ k]
  rw [← integral_finset_sum _ (fun j _ => amplitude_phase_integrable hfm hf hb k _)]
  apply integral_congr_ae
  exact ae_of_all _ fun z => by
    unfold candidateRowFourierSum
    simp_rw [add_mul, phase_add]
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro j hj
    ring

/-- The absolute discrete mean value keeps the exact resonant-frequency
weight and removes the initial endpoint from the upper bound. -/
theorem candidate_fourier_row_power_sum_le {X : Type*} [MeasurableSpace X]
    (ν : Measure X) [SigmaFinite ν] {f : X → ℂ} (hfm : Measurable f)
    (hf : Integrable f ν) {b : X → ℝ} (hb : Measurable b)
    (u h : ℝ) (n k : ℕ) :
    (∑ j ∈ range n, ‖∫ x, f x * candidateCovariancePhase ((u + j * h) * b x) ∂ν‖ ^ (2 * k)) ≤
      ∫ z, ‖candidateRowPowerAmplitude f z‖ *
        ‖candidateRowFourierSum n h (candidateRowPowerFrequency b z)‖
        ∂candidateRowPowerMeasure ν k := by
  have he := congrArg norm (candidate_fourier_row_power_sum_eq ν hfm hf hb u h n k)
  have hn : 0 ≤ ∑ j ∈ range n,
      ‖∫ x, f x * candidateCovariancePhase ((u + j * h) * b x) ∂ν‖ ^ (2 * k) :=
    Finset.sum_nonneg fun _ _ => by positivity
  rw [Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hn] at he
  refine he.le.trans ?_
  convert norm_integral_le_integral_norm _ using 1
  apply integral_congr_ae
  exact ae_of_all _ fun z => by simp only [norm_mul, phase_norm, mul_one]

/-- The finite grid gives the trivial bound also at exact resonances. -/
theorem candidate_rowFourierSum_norm_le_card (n : ℕ) (h x : ℝ) :
    ‖candidateRowFourierSum n h x‖ ≤ n := by
  calc
    _ ≤ ∑ j ∈ range n, ‖candidateCovariancePhase ((j : ℝ) * h * x)‖ := norm_sum_le _ _
    _ = _ := by simp [phase_norm]

/-- Away from resonance the geometric sum has a reciprocal chord bound. -/
theorem candidate_rowFourierSum_norm_mul_chord_le (n : ℕ) (h x : ℝ) :
    ‖candidateRowFourierSum n h x‖ * ‖candidateCovariancePhase (h * x) - 1‖ ≤ 2 := by
  have he (j : ℕ) : candidateCovariancePhase ((j : ℝ) * h * x) =
      candidateCovariancePhase (h * x) ^ j := by
    rw [candidateCovariancePhase, candidateCovariancePhase, ← Complex.exp_nat_mul]
    congr 1
    push_cast
    ring
  have hg := congrArg norm (geom_sum_mul (candidateCovariancePhase (h * x)) n)
  simp only [← he, norm_mul] at hg
  calc
    _ = ‖candidateCovariancePhase ((n : ℝ) * h * x) - 1‖ := hg
    _ ≤ ‖candidateCovariancePhase ((n : ℝ) * h * x)‖ + ‖(1 : ℂ)‖ := norm_sub_le _ _
    _ = _ := by norm_num [phase_norm]

/-- An explicit nonresonant bound with no division by zero convention. -/
theorem candidate_rowFourierSum_norm_le_of_chord_ge (n : ℕ) (h x : ℝ)
    {ε : ℝ} (hε : 0 < ε) (hx : ε ≤ ‖candidateCovariancePhase (h * x) - 1‖) :
    ‖candidateRowFourierSum n h x‖ ≤ min (n : ℝ) (2 / ε) := by
  refine le_min (candidate_rowFourierSum_norm_le_card n h x) ?_
  apply (le_div_iff₀ hε).mpr
  exact (mul_le_mul_of_nonneg_left hx (norm_nonneg _)).trans
    (candidate_rowFourierSum_norm_mul_chord_le n h x)

/-- The retained resonance-weighted product is integrable; subsequent
restrictions and Fubini steps do not require another analytic hypothesis. -/
theorem candidate_integrable_fourier_row_power_weight {X : Type*} [MeasurableSpace X]
    {ν : Measure X} [SigmaFinite ν] {f : X → ℂ} (hfm : Measurable f)
    (hf : Integrable f ν) {b : X → ℝ} (hb : Measurable b) (h : ℝ) (n k : ℕ) :
    Integrable (fun z => ‖candidateRowPowerAmplitude f z‖ *
      ‖candidateRowFourierSum n h (candidateRowPowerFrequency b z)‖)
      (candidateRowPowerMeasure ν k) := by
  apply ((amplitude_integrable hf k).norm.mul_const (n : ℝ)).mono'
  · apply Measurable.aestronglyMeasurable
    unfold candidateRowPowerAmplitude candidateRowFourierSum
      candidateRowPowerFrequency candidateCovariancePhase
    fun_prop
  · exact ae_of_all _ fun z => by
      rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg (norm_nonneg _) (norm_nonneg _))]
      exact mul_le_mul_of_nonneg_left (candidate_rowFourierSum_norm_le_card n h _)
        (norm_nonneg _)

end
end Erdos.Problem1144
