import Erdos.Problem520.Equation16

open Finset MeasureTheory Set
open scoped BigOperators

namespace Erdos
namespace Problem520

/-!
# Routine analytic helpers for equation (16)

This file keeps the finite-coordinate measurability and elementary
integrability facts separate from the probability/analytic assembly in
`Equation16`.  In particular, the smooth block energy only sees the prime
coordinates at most its right endpoint, hence it is automatically integrable
on the infinite product probability space.
-/

private theorem smoothSum_eq_of_eq_on_primesBelow
    {omega omega' : Omega} {z y : ℕ}
    (h : ∀ p ∈ (y + 1).primesBelow, omega p = omega' p) :
    Ψ omega z y = Ψ omega' z y := by
  classical
  simp_rw [Ψ_eq_sum_squarefreeSmoothSets]
  apply Finset.sum_congr rfl
  intro S hS
  unfold freshCharacter
  apply Finset.prod_congr rfl
  intro p hp
  have hpold : p ∈ (y + 1).primesBelow :=
    (mem_squarefreeSmoothSets.mp hS).1 hp
  simp only [ε, h p hpold]

/-- Every prime coordinate visible at a clamped time in `[a,b]` belongs to
the union of the old block and the fresh block. -/
private theorem mem_old_union_fresh_of_mem_primesBelow_freshCutoff
    {a b k p : ℕ} (hab : a ≤ b)
    (hp : p ∈ (freshCutoff a b k + 1).primesBelow) :
    p ∈ (a + 1).primesBelow ∪ freshPrimes a b := by
  have hpinfo := Nat.mem_primesBelow.mp hp
  have hple : p ≤ freshCutoff a b k := Nat.le_of_lt_succ hpinfo.1
  have hpb : p ≤ b := hple.trans (freshCutoff_le hab)
  by_cases hpa : p ≤ a
  · exact Finset.mem_union_left _ <|
      Nat.mem_primesBelow.mpr ⟨by omega, hpinfo.2⟩
  · exact Finset.mem_union_right _ <|
      mem_freshPrimes.mpr ⟨hpinfo.2, Nat.lt_of_not_ge hpa, hpb⟩

/-- The real smooth sum at a clamped block time depends only on the old and
fresh prime coordinates. -/
private theorem ΨReal_freshCutoff_eq_of_eq_on_old_union_fresh
    {omega omega' : Omega} {a b : ℕ} (hab : a ≤ b)
    (h : ∀ p ∈ (a + 1).primesBelow ∪ freshPrimes a b,
      omega p = omega' p)
    (z : ℝ) (k : ℕ) :
    ΨReal omega z (freshCutoff a b k) =
      ΨReal omega' z (freshCutoff a b k) := by
  unfold ΨReal
  apply smoothSum_eq_of_eq_on_primesBelow
  intro p hp
  exact h p (mem_old_union_fresh_of_mem_primesBelow_freshCutoff hab hp)

/-- The pointwise block maximum depends only on the finitely many prime
coordinates in the old and fresh blocks. -/
private theorem realSmoothBlockMaxSq_eq_of_eq_on_old_union_fresh
    {omega omega' : Omega} {a b : ℕ} (hab : a ≤ b)
    (h : ∀ p ∈ (a + 1).primesBelow ∪ freshPrimes a b,
      omega p = omega' p)
    (z : ℝ) :
    realSmoothBlockMaxSq a b omega z =
      realSmoothBlockMaxSq a b omega' z := by
  unfold realSmoothBlockMaxSq finiteRunningMax
  apply Finset.sup'_congr
    (show (Finset.range (b + 1)).Nonempty from
      ⟨0, Finset.mem_range.mpr (Nat.zero_lt_succ b)⟩) rfl
  intro k hk
  change |ΨReal omega z (freshCutoff a b k)| ^ 2 =
    |ΨReal omega' z (freshCutoff a b k)| ^ 2
  rw [ΨReal_freshCutoff_eq_of_eq_on_old_union_fresh hab h z k]

/-- The integrated block energy depends only on the finitely many prime
coordinates at most `b`. -/
theorem realSmoothBlockEnergy_eq_of_eq_on_old_union_fresh
    {omega omega' : Omega} {a b : ℕ} (hab : a ≤ b)
    (h : ∀ p ∈ (a + 1).primesBelow ∪ freshPrimes a b,
      omega p = omega' p) :
    realSmoothBlockEnergy a b omega =
      realSmoothBlockEnergy a b omega' := by
  unfold realSmoothBlockEnergy
  congr 1
  apply setIntegral_congr_fun measurableSet_Ioi
  intro z hz
  change realSmoothBlockMaxSq a b omega z / z ^ 2 =
    realSmoothBlockMaxSq a b omega' z / z ^ 2
  rw [realSmoothBlockMaxSq_eq_of_eq_on_old_union_fresh hab h z]

/-- A power of the concrete block energy is strongly measurable with respect
to the finite sigma algebra generated by the old and fresh prime coordinates.
This discharges the `hdep` hypothesis of
`conditional_realSmoothBlockMoment_le`. -/
theorem stronglyMeasurable_realSmoothBlockEnergy_pow
    {a b r : ℕ} (hab : a ≤ b) :
    StronglyMeasurable[Filtration.piFinset
      ((a + 1).primesBelow ∪ freshPrimes a b)]
        (fun omega : Omega ↦ realSmoothBlockEnergy a b omega ^ r) := by
  classical
  let s : Finset ℕ := (a + 1).primesBelow ∪ freshPrimes a b
  let base : Omega := fun _ ↦ false
  let G : (s → Bool) → ℝ := fun eta ↦
    realSmoothBlockEnergy a b (Function.updateFinset base s eta) ^ r
  have hG : StronglyMeasurable G :=
    (measurable_of_finite G).stronglyMeasurable
  have hcomp : StronglyMeasurable[Filtration.piFinset s]
      (fun omega : Omega ↦ G (s.restrict omega)) :=
    hG.comp_measurable (measurable_restrict_piFinset s)
  have heq : (fun omega : Omega ↦ realSmoothBlockEnergy a b omega ^ r) =
      fun omega : Omega ↦ G (s.restrict omega) := by
    funext omega
    change realSmoothBlockEnergy a b omega ^ r =
      realSmoothBlockEnergy a b
        (Function.updateFinset base s (s.restrict omega)) ^ r
    congr 1
    apply realSmoothBlockEnergy_eq_of_eq_on_old_union_fresh hab
    intro p hp
    change p ∈ s at hp
    simp [Function.updateFinset, hp]
  change StronglyMeasurable[Filtration.piFinset s]
    (fun omega : Omega ↦ realSmoothBlockEnergy a b omega ^ r)
  rw [heq]
  exact hcomp

/-- Finite-coordinate dependence makes every natural power of the block
energy integrable under the infinite fair-coin product law. -/
theorem integrable_realSmoothBlockEnergy_pow
    {a b r : ℕ} (hab : a ≤ b) :
    Integrable (fun omega : Omega ↦ realSmoothBlockEnergy a b omega ^ r) μ :=
  integrable_of_stronglyMeasurable_piFinset
    (stronglyMeasurable_realSmoothBlockEnergy_pow (r := r) hab)

/-! ## Elementary inverse-square kernel integrability -/

private theorem smoothSum_zero_cutoff (omega : Omega) (y : ℕ) :
    Ψ omega 0 y = 0 := by
  have hempty : Nat.smoothNumbersUpTo 0 (y + 1) = ∅ := by
    ext n
    simp only [Nat.mem_smoothNumbersUpTo, Finset.notMem_empty, iff_false]
    rintro ⟨hn, hsmooth⟩
    have hn0 : n = 0 := Nat.eq_zero_of_le_zero hn
    subst n
    exact (Nat.ne_zero_of_mem_smoothNumbers hsmooth) rfl
  unfold Ψ
  rw [hempty]
  simp

/-- A smooth Rademacher sum is uniformly bounded by the number of subsets of
the available prime coordinates.  The bound is deliberately crude but is
uniform in the real cutoff. -/
theorem abs_ΨReal_le_powerset_card (old : Omega) (z : ℝ) (a : ℕ) :
    |ΨReal old z a| ≤ (((a + 1).primesBelow.powerset.card : ℕ) : ℝ) := by
  have hcard : (squarefreeSmoothSets ⌊z⌋₊ a).card ≤
      ((a + 1).primesBelow.powerset).card :=
    Finset.card_le_card (Finset.filter_subset _ _)
  calc
    |ΨReal old z a| = ‖Ψ old ⌊z⌋₊ a‖ := by
      rw [ΨReal, Real.norm_eq_abs]
    _ ≤ (squarefreeSmoothSets ⌊z⌋₊ a).card :=
      norm_Ψ_le_card old ⌊z⌋₊ a
    _ ≤ (((a + 1).primesBelow.powerset.card : ℕ) : ℝ) := by
      exact_mod_cast hcard

/-- The base inverse-square smooth energy is integrable outright.  Near zero
the real-cutoff sum vanishes; from `1` to infinity the preceding finite bound
reduces the kernel to a constant multiple of `z⁻²`. -/
theorem integrableOn_ΨReal_sq_div_sq (old : Omega) (a : ℕ) :
    IntegrableOn (fun z : ℝ ↦ |ΨReal old z a| ^ 2 / z ^ 2)
      (Ioi (0 : ℝ)) := by
  let F : ℝ → ℝ := fun z ↦ |ΨReal old z a| ^ 2 / z ^ 2
  let C : ℝ := (((a + 1).primesBelow.powerset.card : ℕ) : ℝ)
  have hnear : IntegrableOn F (Ioc (0 : ℝ) 1) := by
    rw [integrableOn_Ioc_iff_integrableOn_Ioo' (μ := volume) (by simp)]
    have hzero : EqOn F 0 (Ioo (0 : ℝ) 1) := by
      intro z hz
      have hfloor : ⌊z⌋₊ = 0 := Nat.floor_eq_zero.mpr hz.2
      change F z = 0
      simp [F, ΨReal, hfloor, smoothSum_zero_cutoff]
    exact (integrableOn_zero (μ := volume) (s := Ioo (0 : ℝ) 1)).congr_fun
      hzero.symm measurableSet_Ioo
  have hfarMajor : IntegrableOn
      (fun z : ℝ ↦ C ^ 2 * z ^ (-2 : ℝ)) (Ioi (1 : ℝ)) :=
    (integrableOn_Ioi_rpow_of_lt (by norm_num) zero_lt_one).const_mul _
  have hFmeas : AEStronglyMeasurable F
      (volume.restrict (Ioi (1 : ℝ))) := by
    apply Measurable.aestronglyMeasurable
    exact (((measurable_ΨReal_cutoff old a).abs.pow_const 2).div
      (measurable_id.pow_const 2)).stronglyMeasurable.measurable
  have hfar : IntegrableOn F (Ioi (1 : ℝ)) := by
    refine Integrable.mono' hfarMajor hFmeas ?_
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with z hzmem
    have hPsi : |ΨReal old z a| ≤ C := by
      simpa only [C] using abs_ΨReal_le_powerset_card old z a
    have hC : 0 ≤ C := by positivity
    have hz : 0 < z := zero_lt_one.trans hzmem
    rw [Real.norm_eq_abs, abs_of_nonneg
      (div_nonneg (sq_nonneg _) (sq_nonneg _))]
    calc
      F z ≤ C ^ 2 / z ^ 2 := by
        unfold F
        exact div_le_div_of_nonneg_right
          (pow_le_pow_left₀ (abs_nonneg _) hPsi 2) (sq_nonneg z)
      _ = C ^ 2 * z ^ (-2 : ℝ) := by
        rw [show (-2 : ℝ) = -(2 : ℝ) by norm_num,
          Real.rpow_neg hz.le, Real.rpow_two]
        ring
  rw [← Ioc_union_Ioi_eq_Ioi (show (0 : ℝ) ≤ 1 by norm_num)]
  exact hnear.union hfar

/-- Integrability of the base inverse-square smooth energy is inherited by
every fresh coefficient kernel.  This is the integrability analogue of the
exact dilation identity in `ScalingIntegral` and reduces all coefficient
side conditions in equation (16) to one base-energy hypothesis. -/
theorem integrableOn_realFreshCoefficient_sq_div_sq
    (old : Omega) {a b : ℕ} {S : Finset ℕ}
    (hS : S ∈ (freshPrimes a b).powerset)
    (hbase : IntegrableOn
      (fun w : ℝ ↦ |ΨReal old w a| ^ 2 / w ^ 2) (Ioi (0 : ℝ))) :
    IntegrableOn
      (fun z : ℝ ↦
        |ΨReal old (z / (freshProduct S : ℝ)) a| ^ 2 / z ^ 2)
      (Ioi (0 : ℝ)) := by
  have hSsub : S ⊆ freshPrimes a b := Finset.mem_powerset.mp hS
  have hprime : ∀ p ∈ S, p.Prime := by
    intro p hp
    exact (mem_freshPrimes.mp (hSsub hp)).1
  have hdNat : 0 < freshProduct S := freshProduct_pos_of_primes hprime
  have hd : 0 < (freshProduct S : ℝ) := by exact_mod_cast hdNat
  let d : ℝ := freshProduct S
  let g : ℝ → ℝ := fun w ↦ |ΨReal old w a| ^ 2 / w ^ 2
  have hcomp : IntegrableOn (fun z : ℝ ↦ g (z * d⁻¹)) (Ioi (0 : ℝ)) := by
    exact (integrableOn_Ioi_comp_mul_right_iff g 0 (inv_pos.mpr hd)).2 <| by
      simpa only [g, zero_mul] using hbase
  have hscaled : IntegrableOn
      (fun z : ℝ ↦ d⁻¹ ^ 2 * g (z * d⁻¹)) (Ioi (0 : ℝ)) :=
    hcomp.const_mul _
  refine hscaled.congr_fun ?_ measurableSet_Ioi
  intro z hz
  have hz0 : z ≠ 0 := ne_of_gt hz
  dsimp only [d, g]
  rw [div_eq_mul_inv]
  field_simp [hd.ne', hz0]

/-- Unconditional coefficient-kernel integrability, obtained by combining
the base-energy estimate with inverse-square dilation. -/
theorem integrableOn_realFreshCoefficient_sq_div_sq_of_mem
    (old : Omega) {a b : ℕ} {S : Finset ℕ}
    (hS : S ∈ (freshPrimes a b).powerset) :
    IntegrableOn
      (fun z : ℝ ↦
        |ΨReal old (z / (freshProduct S : ℝ)) a| ^ 2 / z ^ 2)
      (Ioi (0 : ℝ)) :=
  integrableOn_realFreshCoefficient_sq_div_sq old hS
    (integrableOn_ΨReal_sq_div_sq old a)

/-- The rooted finite-fiber smooth-path moment is measurable in the real
cutoff.  It is a step function through the natural floor. -/
theorem measurable_realFrozenSmoothPathMaxMoment
    {a b : ℕ} (old : Omega) (r : ℕ) :
    Measurable fun z : ℝ ↦
      realFrozenSmoothPathMaxMoment (a := a) (b := b) old z r := by
  unfold realFrozenSmoothPathMaxMoment
  exact (measurable_of_countable fun n : ℕ ↦
    frozenSmoothPathMaxMoment (a := a) (b := b) old n r).comp
      Nat.measurable_floor

/-- The real-cutoff rooted maximum moment is nonnegative. -/
theorem realFrozenSmoothPathMaxMoment_nonneg
    {a b : ℕ} (old : Omega) (z : ℝ) (r : ℕ) :
    0 ≤ realFrozenSmoothPathMaxMoment (a := a) (b := b) old z r :=
  frozenSmoothPathMaxMoment_nonneg old ⌊z⌋₊ r

/-- The maximum-moment kernel occurring after Minkowski is integrable.  The
pointwise Doob--Bonami bound dominates it by a finite weighted sum of the
already-integrable coefficient kernels. -/
theorem integrableOn_realFrozenSmoothPathMaxMoment_div_sq_via_bonami
    {a b r : ℕ} (old : Omega) (hab : a ≤ b) (hr : 1 ≤ r) :
    IntegrableOn
      (fun z : ℝ ↦
        realFrozenSmoothPathMaxMoment (a := a) (b := b) old z r / z ^ 2)
      (Ioi (0 : ℝ)) := by
  let P := (freshPrimes a b).powerset
  let weight : Finset ℕ → ℝ := fun S ↦
    ((2 * r - 1 : ℕ) : ℝ) ^ S.card
  let majorant : ℝ → ℝ := fun z ↦
    4 * ∑ S ∈ P, weight S *
      (|ΨReal old (z / (freshProduct S : ℝ)) a| ^ 2 / z ^ 2)
  have hmajorant : IntegrableOn majorant (Ioi (0 : ℝ)) := by
    apply Integrable.const_mul
    apply integrable_finset_sum P
    intro S hS
    apply Integrable.const_mul
    exact integrableOn_realFreshCoefficient_sq_div_sq_of_mem old hS
  have htargetMeas : AEStronglyMeasurable
      (fun z : ℝ ↦
        realFrozenSmoothPathMaxMoment (a := a) (b := b) old z r / z ^ 2)
      (volume.restrict (Ioi (0 : ℝ))) :=
    ((measurable_realFrozenSmoothPathMaxMoment old r).div
      (measurable_id.pow_const 2)).aestronglyMeasurable
  refine Integrable.mono' hmajorant htargetMeas ?_
  filter_upwards [ae_restrict_mem measurableSet_Ioi] with z hz
  have hz2 : 0 ≤ z ^ 2 := sq_nonneg z
  rw [Real.norm_eq_abs, abs_of_nonneg
    (div_nonneg (realFrozenSmoothPathMaxMoment_nonneg old z r) hz2)]
  have hbon := realFrozenSmoothPathMaxMoment_le_bonami old z r hab hr
  calc
    realFrozenSmoothPathMaxMoment (a := a) (b := b) old z r / z ^ 2
        ≤ (4 * ∑ S ∈ P, weight S *
            |ΨReal old (z / (freshProduct S : ℝ)) a| ^ 2) / z ^ 2 := by
          exact div_le_div_of_nonneg_right (by simpa [P, weight] using hbon) hz2
    _ = majorant z := by
      simp only [majorant, div_eq_mul_inv]
      calc
        (4 * ∑ S ∈ P, weight S *
            |ΨReal old (z / (freshProduct S : ℝ)) a| ^ 2) * (z ^ 2)⁻¹ =
            4 * ((∑ S ∈ P, weight S *
              |ΨReal old (z / (freshProduct S : ℝ)) a| ^ 2) *
                (z ^ 2)⁻¹) := by ring
        _ = 4 * ∑ S ∈ P,
            (weight S * |ΨReal old
              (z / (freshProduct S : ℝ)) a| ^ 2) * (z ^ 2)⁻¹ := by
          rw [Finset.sum_mul]
        _ = 4 * ∑ S ∈ P, weight S *
            (|ΨReal old (z / (freshProduct S : ℝ)) a| ^ 2 *
              (z ^ 2)⁻¹) := by
          congr 1
          apply Finset.sum_congr rfl
          intro S hS
          ring

/-! ## Fully assembled concrete block estimate -/

/-- Equation (16) for one concrete natural prime block.  All finite-fiber,
Doob, Bonami, Minkowski, measurability, and integrability obligations are
discharged.  The only remaining inputs are the paper-facing Parseval/energy
comparison and the reciprocal-prime estimate for the chosen schedule block.

The first component is the integrability clause required by
`ThinPrimeBlockMomentBound`; the second component is its conditional moment
inequality. -/
theorem concreteEquation16
    {ell r a b : ℕ} (hell : 0 < ell) (hr : 2 ≤ r)
    (Iold : Omega → ℝ) {Cparseval Crecip : ℝ}
    (hab : a ≤ b) (hlog : 0 < Real.log (b : ℝ))
    (hCparseval : 0 ≤ Cparseval) (hCrecip : 0 ≤ Crecip)
    (hI_nonneg : ∀ old, 0 ≤ Iold old)
    (hparseval : ∀ old,
      (∫ w in Ioi (0 : ℝ), |ΨReal old w a| ^ 2 / w ^ 2) /
          Real.log (b : ℝ) ≤ Cparseval * Iold old)
    (hrecip : freshReciprocalSum a b ≤ Crecip / ell) :
    Integrable (fun omega ↦ realSmoothBlockEnergy a b omega ^ r) μ ∧
      (let C := max (4 * Cparseval) (2 * Crecip)
       ∀ᵐ old ∂μ,
        (μ[(fun omega ↦ realSmoothBlockEnergy a b omega ^ r) |
            Filtration.piFinset ((a + 1).primesBelow)] old) ^
              (1 / (r : ℝ)) ≤
          C * Real.exp (C * r / ell) * Iold old) := by
  constructor
  · exact integrable_realSmoothBlockEnergy_pow (r := r) hab
  · exact conditional_realSmoothBlockMoment_le hell hr Iold hab hlog
      hCparseval hCrecip hI_nonneg
      (stronglyMeasurable_realSmoothBlockEnergy_pow (r := r) hab)
      (fun old v ↦ integrableOn_realFrozenSmoothPathMaxSq_div_sq old v hab)
      (fun old ↦ integrableOn_realFrozenSmoothPathMaxMoment_div_sq_via_bonami
        old hab (by omega))
      (fun old S hS ↦ integrableOn_realFreshCoefficient_sq_div_sq_of_mem old hS)
      hparseval hrecip

end Problem520
end Erdos
