import Erdos.Problem520.FreshExpansion
import Erdos.Problem520.Doob
import Mathlib.Probability.BorelCantelli

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal NNReal

namespace Erdos
namespace Problem520

/-!
# The finite fresh-prime Doob martingale

This file freezes every coordinate outside a prime block `(a,b]`, puts the
finite product coin law on the remaining coordinates, and takes the canonical
Doob martingale of the terminal smooth sum.  In particular, no regular
conditional-probability API on the original infinite product space is needed.
-/

/-- The finite type of prime coordinates in `(a,b]`. -/
abbrev FreshIndex (a b : ℕ) := {p : ℕ // p ∈ freshPrimes a b}

/-- Assignments of Boolean signs to the primes in `(a,b]`. -/
abbrev FreshCube (a b : ℕ) := FreshIndex a b → Bool

/-- The finite product of fair coin laws on a fresh prime block. -/
noncomputable def freshCubeLaw (a b : ℕ) : Measure (FreshCube a b) :=
  Measure.pi fun _ : FreshIndex a b ↦ coin

instance freshCubeLaw_isProbabilityMeasure (a b : ℕ) :
    IsProbabilityMeasure (freshCubeLaw a b) := by
  unfold freshCubeLaw
  infer_instance

/-- Replace the coordinates in `(a,b]` by a fresh-cube assignment, leaving
all other coordinates frozen. -/
def spliceFresh {a b : ℕ} (old : Omega) (v : FreshCube a b) : Omega :=
  fun p ↦ if hp : p ∈ freshPrimes a b then v ⟨p, hp⟩ else old p

@[simp] theorem spliceFresh_of_mem {a b p : ℕ} (old : Omega)
    (v : FreshCube a b) (hp : p ∈ freshPrimes a b) :
    spliceFresh old v p = v ⟨p, hp⟩ := by
  simp [spliceFresh, hp]

@[simp] theorem spliceFresh_of_not_mem {a b p : ℕ} (old : Omega)
    (v : FreshCube a b) (hp : p ∉ freshPrimes a b) :
    spliceFresh old v p = old p := by
  simp [spliceFresh, hp]

/-- At time `k`, reveal the fresh coordinate `k` if it belongs to the block;
at non-fresh indices the revealed variable is the constant `false`. -/
def freshReveal (a b k : ℕ) (v : FreshCube a b) : Bool :=
  if hk : k ∈ freshPrimes a b then v ⟨k, hk⟩ else false

theorem stronglyMeasurable_freshReveal (a b k : ℕ) :
    StronglyMeasurable (freshReveal a b k) := by
  exact (measurable_of_finite _).stronglyMeasurable

/-- The genuine fresh coordinates are independent under the finite product
law. -/
theorem iIndepFun_freshCube_coordinates (a b : ℕ) :
    iIndepFun (fun q : FreshIndex a b ↦ fun v : FreshCube a b ↦ v q)
      (freshCubeLaw a b) := by
  unfold freshCubeLaw
  exact iIndepFun_pi (X := fun _ : FreshIndex a b ↦ id)
    (fun _ ↦ aemeasurable_id)

/-- The filtration generated by revealing fresh coordinates in numerical
order. -/
noncomputable def freshFiltration (a b : ℕ) :
    Filtration ℕ (inferInstance : MeasurableSpace (FreshCube a b)) :=
  Filtration.natural (freshReveal a b) (stronglyMeasurable_freshReveal a b)

/-- The information generated by the numerical reveal process up to `k` is
contained in the join of the genuine fresh coordinates whose prime value is
at most `k`. -/
theorem freshFiltration_le_iSup_coordinates (a b k : ℕ) :
    freshFiltration a b k ≤
      ⨆ q : FreshIndex a b, ⨆ _h : q.1 ≤ k,
        MeasurableSpace.comap (fun v : FreshCube a b ↦ v q)
          (inferInstance : MeasurableSpace Bool) := by
  rw [freshFiltration]
  refine iSup₂_le fun j hj ↦ ?_
  by_cases hjfresh : j ∈ freshPrimes a b
  · have heq : freshReveal a b j =
        (fun v : FreshCube a b ↦ v ⟨j, hjfresh⟩) := by
      funext v
      simp [freshReveal, hjfresh]
    rw [heq]
    exact le_iSup₂_of_le (⟨j, hjfresh⟩ : FreshIndex a b) hj le_rfl
  · have heq : freshReveal a b j = (fun _ : FreshCube a b ↦ false) := by
      funext v
      simp [freshReveal, hjfresh]
    rw [heq]
    exact measurable_const.comap_le

/-- A not-yet-revealed genuine fresh coordinate is independent of the current
fresh filtration. -/
theorem indep_freshCoordinate_freshFiltration {a b k : ℕ}
    (q : FreshIndex a b) (hq : k < q.1) :
    Indep
      (MeasurableSpace.comap (fun v : FreshCube a b ↦ v q)
        (inferInstance : MeasurableSpace Bool))
      (freshFiltration a b k) (freshCubeLaw a b) := by
  let coordMS : FreshIndex a b → MeasurableSpace (FreshCube a b) :=
    fun t ↦ MeasurableSpace.comap (fun v : FreshCube a b ↦ v t)
      (inferInstance : MeasurableSpace Bool)
  have hle : ∀ t, coordMS t ≤
      (inferInstance : MeasurableSpace (FreshCube a b)) := fun t ↦
    (measurable_pi_apply t).comap_le
  have hind : iIndep coordMS (freshCubeLaw a b) := by
    exact (iIndepFun_freshCube_coordinates a b).iIndep
  have hdisj : Disjoint ({q} : Set (FreshIndex a b)) {t | t.1 ≤ k} := by
    rw [Set.disjoint_left]
    intro t htq htk
    simp only [Set.mem_singleton_iff] at htq
    subst t
    exact (Nat.not_le_of_gt hq) htk
  have hlarge := indep_iSup_of_disjoint hle hind hdisj
  have hcoord : Indep (coordMS q)
      (⨆ t : FreshIndex a b, ⨆ _h : t.1 ≤ k, coordMS t)
      (freshCubeLaw a b) := by
    simpa only [iSup_singleton] using hlarge
  apply indep_of_indep_of_le_right hcoord
  exact freshFiltration_le_iSup_coordinates a b k

/-- The centered real sign attached to a finite-cube coordinate. -/
def freshCubeSign {a b : ℕ} (q : FreshIndex a b) (v : FreshCube a b) : ℝ :=
  if v q then 1 else -1

theorem integral_freshCubeSign {a b : ℕ} (q : FreshIndex a b) :
    ∫ v, freshCubeSign q v ∂freshCubeLaw a b = 0 := by
  let g : Bool → ℝ := fun x ↦ if x then 1 else -1
  calc
    (∫ v, freshCubeSign q v ∂freshCubeLaw a b) =
        ∫ v, g (v q) ∂freshCubeLaw a b := by rfl
    _ = ∫ x, g x ∂Measure.map (fun v : FreshCube a b ↦ v q)
        (freshCubeLaw a b) := by
      symm
      exact integral_map (measurable_pi_apply q).aemeasurable
        (measurable_of_finite g).aestronglyMeasurable
    _ = ∫ x, g x ∂coin := by
      unfold freshCubeLaw
      rw [(MeasureTheory.measurePreserving_eval
        (fun _ : FreshIndex a b ↦ coin) q).map_eq]
    _ = 0 := by
      have hgfalse : Integrable g ((1 / 2 : ℝ≥0∞) • Measure.dirac false) :=
        (integrable_dirac (f := g) (by simp)).smul_measure (by norm_num)
      have hgtrue : Integrable g ((1 / 2 : ℝ≥0∞) • Measure.dirac true) :=
        (integrable_dirac (f := g) (by simp)).smul_measure (by norm_num)
      rw [coin, integral_add_measure hgfalse hgtrue,
        integral_smul_measure, integral_smul_measure]
      norm_num [g]

/-- A genuinely future fresh sign has conditional expectation zero. -/
theorem condExp_freshCubeSign_eq_zero {a b k : ℕ}
    (q : FreshIndex a b) (hq : k < q.1) :
    (freshCubeLaw a b)[freshCubeSign q | freshFiltration a b k] =ᵐ[
        freshCubeLaw a b] (0 : FreshCube a b → ℝ) := by
  have hsign : StronglyMeasurable[
      MeasurableSpace.comap (fun v : FreshCube a b ↦ v q)
        (inferInstance : MeasurableSpace Bool)] (freshCubeSign q) := by
    exact (measurable_of_finite (fun x : Bool ↦ if x then (1 : ℝ) else -1))
      |>.stronglyMeasurable.comp_measurable
        (comap_measurable fun v : FreshCube a b ↦ v q)
  have h := condExp_indep_eq
    (measurable_pi_apply q).comap_le
    ((freshFiltration a b).le k)
    hsign
    (indep_freshCoordinate_freshFiltration q hq)
  exact h.trans (ae_of_all (freshCubeLaw a b) fun _ ↦ integral_freshCubeSign q)

/-- A spliced sign is measurable as soon as its (fresh) coordinate has been
revealed.  Coordinates outside the block are frozen constants. -/
theorem stronglyMeasurable_ε_splice_freshFiltration {a b p k : ℕ}
    (old : Omega) (hp : p ∈ freshPrimes a b → p ≤ k) :
    StronglyMeasurable[freshFiltration a b k]
      (fun v : FreshCube a b ↦ ε (spliceFresh old v) p) := by
  by_cases hpfresh : p ∈ freshPrimes a b
  · have hpk : p ≤ k := hp hpfresh
    have hr := (Filtration.stronglyAdapted_natural
      (stronglyMeasurable_freshReveal a b) p).mono
        ((freshFiltration a b).mono hpk)
    have hs : StronglyMeasurable[freshFiltration a b k]
        (fun v : FreshCube a b ↦
          if freshReveal a b p v then (1 : ℝ) else -1) :=
      (measurable_of_finite (fun x : Bool ↦ if x then (1 : ℝ) else -1))
        |>.stronglyMeasurable.comp_measurable hr.measurable
    convert hs using 1
    funext v
    simp [freshReveal, hpfresh, spliceFresh, ε]
  · have heq : (fun v : FreshCube a b ↦ ε (spliceFresh old v) p) =
        fun _ ↦ ε old p := by
      funext v
      simp [spliceFresh, hpfresh, ε]
    rw [heq]
    exact stronglyMeasurable_const

/-- A spliced Walsh character is measurable once all of its fresh
coordinates have been revealed. -/
theorem stronglyMeasurable_freshCharacter_splice_freshFiltration
    {a b k : ℕ} (old : Omega) {S : Finset ℕ}
    (hS : ∀ p ∈ S, p ∈ freshPrimes a b → p ≤ k) :
    StronglyMeasurable[freshFiltration a b k]
      (fun v : FreshCube a b ↦ freshCharacter (spliceFresh old v) S) := by
  classical
  unfold freshCharacter
  exact Finset.stronglyMeasurable_fun_prod S fun p hp ↦
    stronglyMeasurable_ε_splice_freshFiltration old (hS p hp)

/-- A frozen smooth sum is measurable at any time by which every fresh prime
below its smooth cutoff has been revealed. -/
theorem stronglyMeasurable_Ψ_splice_freshFiltration {a b c k : ℕ}
    (old : Omega) (z : ℕ)
    (hck : ∀ p, p ∈ freshPrimes a b → p ≤ c → p ≤ k) :
    StronglyMeasurable[freshFiltration a b k]
      (fun v : FreshCube a b ↦ Ψ (spliceFresh old v) z c) := by
  classical
  simp_rw [Ψ_eq_sum_squarefreeSmoothSets]
  apply Finset.stronglyMeasurable_fun_sum
  intro S hS
  apply stronglyMeasurable_freshCharacter_splice_freshFiltration old
  intro p hpS hpfresh
  have hsub := (mem_squarefreeSmoothSets.mp hS).1 hpS
  exact hck p hpfresh (Nat.le_of_lt_succ (Nat.mem_primesBelow.mp hsub).1)

/-- Clamp a numerical reveal time to the interval `[a,b]`. -/
def freshCutoff (a b k : ℕ) : ℕ := max a (min k b)

theorem freshCutoff_eq_a {a b k : ℕ} (_hab : a ≤ b) (hk : k ≤ a) :
    freshCutoff a b k = a := by
  unfold freshCutoff
  omega

theorem freshCutoff_eq_self {a b k : ℕ} (hak : a ≤ k) (hkb : k ≤ b) :
    freshCutoff a b k = k := by
  unfold freshCutoff
  omega

theorem freshCutoff_eq_b {a b k : ℕ} (hab : a ≤ b) (hbk : b ≤ k) :
    freshCutoff a b k = b := by
  unfold freshCutoff
  omega

theorem freshCutoff_le {a b k : ℕ} (hab : a ≤ b) :
    freshCutoff a b k ≤ b := by
  unfold freshCutoff
  omega

/-- The concrete frozen smooth-partial-sum path.  It is held constant before
`a` and after `b`, and between those endpoints it is exactly `Ψ(·,z,k)`. -/
noncomputable def frozenSmoothPath {a b : ℕ} (old : Omega) (z : ℕ) :
    ℕ → FreshCube a b → ℝ :=
  fun k v ↦ Ψ (spliceFresh old v) z (freshCutoff a b k)

theorem frozenSmoothPath_of_le_a {a b k : ℕ} (old : Omega) (z : ℕ)
    (hab : a ≤ b) (hk : k ≤ a) :
    frozenSmoothPath (a := a) (b := b) old z k =
      fun v ↦ Ψ (spliceFresh old v) z a := by
  funext v
  simp [frozenSmoothPath, freshCutoff_eq_a hab hk]

theorem frozenSmoothPath_of_mem {a b k : ℕ} (old : Omega) (z : ℕ)
    (hak : a ≤ k) (hkb : k ≤ b) :
    frozenSmoothPath (a := a) (b := b) old z k =
      fun v ↦ Ψ (spliceFresh old v) z k := by
  funext v
  simp [frozenSmoothPath, freshCutoff_eq_self hak hkb]

theorem frozenSmoothPath_of_ge_b {a b k : ℕ} (old : Omega) (z : ℕ)
    (hab : a ≤ b) (hk : b ≤ k) :
    frozenSmoothPath (a := a) (b := b) old z k =
      fun v ↦ Ψ (spliceFresh old v) z b := by
  funext v
  simp [frozenSmoothPath, freshCutoff_eq_b hab hk]

/-- The concrete frozen path is adapted to the finite fresh-coordinate
filtration. -/
theorem stronglyMeasurable_frozenSmoothPath {a b : ℕ}
    (old : Omega) (z : ℕ) (_hab : a ≤ b) (k : ℕ) :
    StronglyMeasurable[freshFiltration a b k]
      (frozenSmoothPath (a := a) (b := b) old z k) := by
  apply stronglyMeasurable_Ψ_splice_freshFiltration old z
  intro p hpfresh hpc
  have hpa : a < p := (mem_freshPrimes.mp hpfresh).2.1
  have hpb : p ≤ b := (mem_freshPrimes.mp hpfresh).2.2
  unfold freshCutoff at hpc
  omega

theorem integrable_frozenSmoothPath {a b : ℕ}
    (old : Omega) (z k : ℕ) :
    Integrable (frozenSmoothPath (a := a) (b := b) old z k)
      (freshCubeLaw a b) := by
  exact Integrable.of_finite

/-- The one-step conditional-expectation identity for the concrete frozen
smooth path. -/
theorem condExp_frozenSmoothPath_succ {a b : ℕ}
    (old : Omega) (z : ℕ) (hab : a ≤ b) (k : ℕ) :
    (freshCubeLaw a b)[
        frozenSmoothPath (a := a) (b := b) old z (k + 1) |
        freshFiltration a b k] =ᵐ[freshCubeLaw a b]
      frozenSmoothPath (a := a) (b := b) old z k := by
  by_cases hka : k < a
  · have hk : k ≤ a := hka.le
    have hk1 : k + 1 ≤ a := by omega
    have heq : frozenSmoothPath (a := a) (b := b) old z (k + 1) =
        frozenSmoothPath (a := a) (b := b) old z k := by
      rw [frozenSmoothPath_of_le_a old z hab hk1,
        frozenSmoothPath_of_le_a old z hab hk]
    rw [heq]
    rw [condExp_of_stronglyMeasurable ((freshFiltration a b).le k)
      (stronglyMeasurable_frozenSmoothPath old z hab k)
      (integrable_frozenSmoothPath old z k)]
  · have hak : a ≤ k := Nat.le_of_not_gt hka
    by_cases hbk : b ≤ k
    · have heq : frozenSmoothPath (a := a) (b := b) old z (k + 1) =
          frozenSmoothPath (a := a) (b := b) old z k := by
        rw [frozenSmoothPath_of_ge_b old z hab (hbk.trans (Nat.le_succ k)),
          frozenSmoothPath_of_ge_b old z hab hbk]
      rw [heq]
      rw [condExp_of_stronglyMeasurable ((freshFiltration a b).le k)
        (stronglyMeasurable_frozenSmoothPath old z hab k)
        (integrable_frozenSmoothPath old z k)]
    · have hkb : k < b := Nat.lt_of_not_ge hbk
      have hk1b : k + 1 ≤ b := by omega
      by_cases hp : (k + 1).Prime
      · have hqmem : k + 1 ∈ freshPrimes a b := by
          rw [mem_freshPrimes]
          exact ⟨hp, by omega, hk1b⟩
        let q : FreshIndex a b := ⟨k + 1, hqmem⟩
        let c : FreshCube a b → ℝ := fun v ↦
          Ψ (spliceFresh old v) (z / (k + 1)) k
        have hc_meas : StronglyMeasurable[freshFiltration a b k] c := by
          apply stronglyMeasurable_Ψ_splice_freshFiltration old (z / (k + 1))
          intro p _hpfresh hpk
          exact hpk
        have hc_int : Integrable c (freshCubeLaw a b) := Integrable.of_finite
        have hsign_int : Integrable (freshCubeSign q) (freshCubeLaw a b) :=
          Integrable.of_finite
        have hprod_int : Integrable
            (fun v ↦ c v * freshCubeSign q v) (freshCubeLaw a b) :=
          Integrable.of_finite
        have hpull :
            (freshCubeLaw a b)[fun v ↦ c v * freshCubeSign q v |
                freshFiltration a b k] =ᵐ[freshCubeLaw a b]
              fun v ↦ c v *
                ((freshCubeLaw a b)[freshCubeSign q | freshFiltration a b k]) v :=
          condExp_mul_of_stronglyMeasurable_left hc_meas hprod_int hsign_int
        have hsignzero := condExp_freshCubeSign_eq_zero
          (a := a) (b := b) (k := k) q (by simp [q])
        have hinczero :
            (freshCubeLaw a b)[fun v ↦ freshCubeSign q v * c v |
                freshFiltration a b k] =ᵐ[freshCubeLaw a b]
              (0 : FreshCube a b → ℝ) := by
          calc
            (freshCubeLaw a b)[fun v ↦ freshCubeSign q v * c v |
                freshFiltration a b k] =ᵐ[freshCubeLaw a b]
                (freshCubeLaw a b)[fun v ↦ c v * freshCubeSign q v |
                  freshFiltration a b k] :=
              condExp_congr_ae (ae_of_all (freshCubeLaw a b) fun _ ↦ mul_comm _ _)
            _ =ᵐ[freshCubeLaw a b] fun v ↦ c v *
                ((freshCubeLaw a b)[freshCubeSign q | freshFiltration a b k]) v := hpull
            _ =ᵐ[freshCubeLaw a b] 0 := by
              filter_upwards [hsignzero] with v hv
              simp [hv]
        have hrec :
            frozenSmoothPath (a := a) (b := b) old z (k + 1) =
              frozenSmoothPath (a := a) (b := b) old z k +
                fun v ↦ freshCubeSign q v * c v := by
          funext v
          simp only [frozenSmoothPath,
            freshCutoff_eq_self hak hkb.le,
            freshCutoff_eq_self (by omega : a ≤ k + 1) hk1b,
            Pi.add_apply]
          have hr := Ψ_recurrence (spliceFresh old v) z (Nat.succ_pos k)
          simp only [hp, if_true] at hr
          rw [hr]
          congr 1
          simp [q, c, freshCubeSign, spliceFresh, hqmem, ε]
        rw [hrec]
        have hbase :
            (freshCubeLaw a b)[
                frozenSmoothPath (a := a) (b := b) old z k |
                freshFiltration a b k] =ᵐ[freshCubeLaw a b]
              frozenSmoothPath (a := a) (b := b) old z k := by
          rw [condExp_of_stronglyMeasurable ((freshFiltration a b).le k)
            (stronglyMeasurable_frozenSmoothPath old z hab k)
            (integrable_frozenSmoothPath old z k)]
        exact (condExp_add (integrable_frozenSmoothPath old z k)
          ((integrable_congr (ae_of_all (freshCubeLaw a b) fun _ ↦ mul_comm _ _)).mpr
            hprod_int) (freshFiltration a b k)).trans
          (by simpa only [Pi.add_apply, Pi.zero_apply, add_zero] using hbase.add hinczero)
      · have heq : frozenSmoothPath (a := a) (b := b) old z (k + 1) =
            frozenSmoothPath (a := a) (b := b) old z k := by
          funext v
          simp only [frozenSmoothPath,
            freshCutoff_eq_self hak hkb.le,
            freshCutoff_eq_self (by omega : a ≤ k + 1) hk1b]
          simpa [hp] using
            Ψ_recurrence (spliceFresh old v) z (Nat.succ_pos k)
        rw [heq]
        rw [condExp_of_stronglyMeasurable ((freshFiltration a b).le k)
          (stronglyMeasurable_frozenSmoothPath old z hab k)
          (integrable_frozenSmoothPath old z k)]

/-- The actual frozen smooth partial sums form a finite-cube martingale. -/
theorem frozenSmoothPath_martingale {a b : ℕ}
    (old : Omega) (z : ℕ) (hab : a ≤ b) :
    Martingale (frozenSmoothPath (a := a) (b := b) old z)
      (freshFiltration a b) (freshCubeLaw a b) := by
  apply martingale_nat
    (fun k ↦ stronglyMeasurable_frozenSmoothPath old z hab k)
    (integrable_frozenSmoothPath old z)
  intro k
  exact (condExp_frozenSmoothPath_succ old z hab k).symm

/-- The terminal smooth sum after the old coordinates have been frozen. -/
noncomputable def frozenSmoothTerminal {a b : ℕ} (old : Omega) (z : ℕ) :
    FreshCube a b → ℝ :=
  fun v ↦ Ψ (spliceFresh old v) z b

/-- The terminal variable is exactly the fresh Walsh expansion from (18),
with the outside assignment frozen at `old`. -/
theorem frozenSmoothTerminal_eq_freshWalshExpansion {a b : ℕ}
    (old : Omega) (z : ℕ) (hab : a ≤ b) (v : FreshCube a b) :
    frozenSmoothTerminal (a := a) (b := b) old z v =
      freshWalshExpansion (spliceFresh old v) z a b := by
  exact Ψ_eq_freshWalshExpansion (spliceFresh old v) z hab

theorem stronglyMeasurable_frozenSmoothTerminal {a b : ℕ}
    (old : Omega) (z : ℕ) :
    StronglyMeasurable (frozenSmoothTerminal (a := a) (b := b) old z) := by
  exact (measurable_of_finite _).stronglyMeasurable

/-- By time `b` every coordinate of the finite fresh cube has been revealed. -/
theorem stronglyMeasurable_id_freshFiltration_terminal (a b : ℕ) :
    StronglyMeasurable[freshFiltration a b b] (id : FreshCube a b → FreshCube a b) := by
  have hmeas : Measurable[freshFiltration a b b]
      (id : FreshCube a b → FreshCube a b) := by
    refine @measurable_pi_lambda (FreshCube a b) (FreshIndex a b) (fun _ ↦ Bool)
      (freshFiltration a b b) (fun _ ↦ inferInstance) id (fun q ↦ ?_)
    have hqb : q.1 ≤ b := (mem_freshPrimes.mp q.2).2.2
    have hq := (Filtration.stronglyAdapted_natural
      (stronglyMeasurable_freshReveal a b) q.1).mono
        ((freshFiltration a b).mono hqb)
    have heq : (fun v : FreshCube a b ↦ freshReveal a b q.1 v) =
        fun v ↦ v q := by
      funext v
      simp [freshReveal, q.2]
    change Measurable[freshFiltration a b b] (fun v : FreshCube a b ↦ v q)
    rw [← heq]
    simpa [freshFiltration] using hq.measurable
  exact hmeas.stronglyMeasurable

/-- The frozen terminal sum is measurable with respect to the information
available after the complete block has been revealed. -/
theorem stronglyMeasurable_frozenSmoothTerminal_at_terminal {a b : ℕ}
    (old : Omega) (z : ℕ) :
    StronglyMeasurable[freshFiltration a b b]
      (frozenSmoothTerminal (a := a) (b := b) old z) := by
  exact (stronglyMeasurable_frozenSmoothTerminal old z).comp_measurable
    (stronglyMeasurable_id_freshFiltration_terminal a b).measurable

theorem integrable_frozenSmoothTerminal {a b : ℕ}
    (old : Omega) (z : ℕ) :
    Integrable (frozenSmoothTerminal (a := a) (b := b) old z)
      (freshCubeLaw a b) := by
  exact Integrable.of_finite

/-- The canonical finite-cube Doob martingale of the frozen terminal smooth
sum. -/
noncomputable def frozenSmoothDoob {a b : ℕ} (old : Omega) (z : ℕ) :
    ℕ → FreshCube a b → ℝ :=
  fun k ↦ (freshCubeLaw a b)[
    frozenSmoothTerminal (a := a) (b := b) old z | freshFiltration a b k]

theorem frozenSmoothDoob_martingale {a b : ℕ} (old : Omega) (z : ℕ) :
    Martingale (frozenSmoothDoob (a := a) (b := b) old z)
      (freshFiltration a b) (freshCubeLaw a b) := by
  exact martingale_condExp
    (frozenSmoothTerminal (a := a) (b := b) old z)
    (freshFiltration a b) (freshCubeLaw a b)

/-- At the terminal time, the canonical Doob process is exactly the frozen
smooth sum (as functions, not merely almost everywhere). -/
theorem frozenSmoothDoob_terminal {a b : ℕ} (old : Omega) (z : ℕ) :
    frozenSmoothDoob (a := a) (b := b) old z b =
      frozenSmoothTerminal (a := a) (b := b) old z := by
  unfold frozenSmoothDoob
  exact condExp_of_stronglyMeasurable ((freshFiltration a b).le b)
    (stronglyMeasurable_frozenSmoothTerminal_at_terminal old z)
    (integrable_frozenSmoothTerminal old z)

/-- Up to the terminal endpoint, the canonical conditional-expectation
process agrees almost everywhere with the concrete frozen smooth partial
sums. -/
theorem frozenSmoothDoob_ae_eq_frozenSmoothPath {a b k : ℕ}
    (old : Omega) (z : ℕ) (hab : a ≤ b) (hkb : k ≤ b) :
    frozenSmoothDoob (a := a) (b := b) old z k =ᵐ[freshCubeLaw a b]
      frozenSmoothPath (a := a) (b := b) old z k := by
  have hb : frozenSmoothPath (a := a) (b := b) old z b =
      frozenSmoothTerminal (a := a) (b := b) old z := by
    simpa only [frozenSmoothTerminal] using
      frozenSmoothPath_of_ge_b (a := a) (b := b) old z hab le_rfl
  have hmart := frozenSmoothPath_martingale old z hab
  unfold frozenSmoothDoob
  exact (condExp_congr_ae (ae_of_all (freshCubeLaw a b) fun v ↦
    congrFun hb.symm v)).trans (hmart.condExp_ae_eq hkb)

/-- Equation (17) on the exact finite fresh-sign probability space.

The old assignment and the smooth cutoff are arbitrary and occur pointwise as
parameters.  The maximum is over the successive numerical reveal times up to
the terminal endpoint `b`; non-fresh times add only constant coordinates to
the natural filtration. -/
theorem frozenSmoothDoob_evenMoment_le {a b : ℕ}
    (old : Omega) (z r : ℕ) :
    ∫ v, finiteRunningMax
          (fun k v ↦ |frozenSmoothDoob (a := a) (b := b) old z k v| ^ r)
          b v ^ 2 ∂freshCubeLaw a b ≤
      4 * ∫ v, |frozenSmoothTerminal (a := a) (b := b) old z v| ^ (2 * r)
        ∂freshCubeLaw a b := by
  have hX := frozenSmoothDoob_martingale (a := a) (b := b) old z
  have hint : ∀ k, Integrable
      (fun v ↦ |frozenSmoothDoob (a := a) (b := b) old z k v| ^ r)
      (freshCubeLaw a b) := fun _ ↦ Integrable.of_finite
  have hbase : Integrable
      (fun v ↦ |frozenSmoothDoob (a := a) (b := b) old z b v| ^ r)
      (freshCubeLaw a b) := Integrable.of_finite
  have hterminal : MemLp
      (fun v ↦ |frozenSmoothDoob (a := a) (b := b) old z b v| ^ r) 2
      (freshCubeLaw a b) :=
    (memLp_two_iff_integrable_sq hbase.aestronglyMeasurable).2 Integrable.of_finite
  have h := Martingale.integral_sq_finiteRunningMax_abs_pow_le
    hX r b hint hterminal
  simpa only [frozenSmoothDoob_terminal] using h

/-- Equation (17) for the actual smooth partial sums on the frozen finite
fresh-prime fiber. -/
theorem frozenSmoothPath_evenMoment_le {a b : ℕ}
    (old : Omega) (z r : ℕ) (hab : a ≤ b) :
    ∫ v, finiteRunningMax
          (fun k v ↦ |frozenSmoothPath (a := a) (b := b) old z k v| ^ r)
          b v ^ 2 ∂freshCubeLaw a b ≤
      4 * ∫ v, |frozenSmoothTerminal (a := a) (b := b) old z v| ^ (2 * r)
        ∂freshCubeLaw a b := by
  have hX := frozenSmoothPath_martingale old z hab
  have hint : ∀ k, Integrable
      (fun v ↦ |frozenSmoothPath (a := a) (b := b) old z k v| ^ r)
      (freshCubeLaw a b) := fun _ ↦ Integrable.of_finite
  have hbase : Integrable
      (fun v ↦ |frozenSmoothPath (a := a) (b := b) old z b v| ^ r)
      (freshCubeLaw a b) := Integrable.of_finite
  have hterminal : MemLp
      (fun v ↦ |frozenSmoothPath (a := a) (b := b) old z b v| ^ r) 2
      (freshCubeLaw a b) :=
    (memLp_two_iff_integrable_sq hbase.aestronglyMeasurable).2 Integrable.of_finite
  have h := Martingale.integral_sq_finiteRunningMax_abs_pow_le
    hX r b hint hterminal
  have hb : frozenSmoothPath (a := a) (b := b) old z b =
      frozenSmoothTerminal (a := a) (b := b) old z := by
    simpa only [frozenSmoothTerminal] using
      frozenSmoothPath_of_ge_b (a := a) (b := b) old z hab le_rfl
  simpa only [hb] using h

/-- The same concrete equation (17), with its terminal moment rewritten as
the Walsh expansion (18). -/
theorem frozenSmoothPath_evenMoment_le_freshWalsh {a b : ℕ}
    (old : Omega) (z r : ℕ) (hab : a ≤ b) :
    ∫ v, finiteRunningMax
          (fun k v ↦ |frozenSmoothPath (a := a) (b := b) old z k v| ^ r)
          b v ^ 2 ∂freshCubeLaw a b ≤
      4 * ∫ v,
        |freshWalshExpansion (spliceFresh old v) z a b| ^ (2 * r)
        ∂freshCubeLaw a b := by
  simpa only [frozenSmoothTerminal_eq_freshWalshExpansion old z hab] using
    frozenSmoothPath_evenMoment_le (a := a) (b := b) old z r hab

/-- Equation (17) with the terminal side displayed as the concrete Walsh
polynomial (18). -/
theorem frozenSmoothDoob_evenMoment_le_freshWalsh {a b : ℕ}
    (old : Omega) (z r : ℕ) (hab : a ≤ b) :
    ∫ v, finiteRunningMax
          (fun k v ↦ |frozenSmoothDoob (a := a) (b := b) old z k v| ^ r)
          b v ^ 2 ∂freshCubeLaw a b ≤
      4 * ∫ v,
        |freshWalshExpansion (spliceFresh old v) z a b| ^ (2 * r)
        ∂freshCubeLaw a b := by
  simpa only [frozenSmoothTerminal_eq_freshWalshExpansion old z hab] using
    frozenSmoothDoob_evenMoment_le (a := a) (b := b) old z r

end Problem520
end Erdos
