import Erdos.Problem520.FreshExpansion
import Mathlib.Probability.BorelCantelli
import Mathlib.Probability.Martingale.Basic

open Finset MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal MeasureTheory

namespace Erdos
namespace Problem520

/-! # The smooth-prime martingale

For fixed `z`, the process `p ↦ Ψ ω z p` reveals the Rademacher
coordinates in their natural order.  This file records the concrete
adaptedness, square-integrability, and martingale statements needed to feed the
finite-time Doob estimate.
-/

/-- The coordinate process whose natural filtration reveals the signs in
increasing order. -/
def εProcess (p : ℕ) (omega : Omega) : ℝ := ε omega p

theorem stronglyMeasurable_εProcess (p : ℕ) :
    StronglyMeasurable (εProcess p) :=
  (measurable_ε p).stronglyMeasurable

/-- Natural filtration generated by all Rademacher coordinates up to `p`. -/
noncomputable def εFiltration :
    Filtration ℕ (inferInstance : MeasurableSpace Omega) :=
  Filtration.natural εProcess stronglyMeasurable_εProcess

theorem stronglyAdapted_εProcess :
    StronglyAdapted εFiltration εProcess :=
  Filtration.stronglyAdapted_natural stronglyMeasurable_εProcess

theorem stronglyMeasurable_ε_filtration {q p : ℕ} (hqp : q ≤ p) :
    StronglyMeasurable[εFiltration p] (fun omega : Omega => ε omega q) := by
  exact (stronglyAdapted_εProcess q).mono (εFiltration.mono hqp)

/-- A Walsh character supported on coordinates at most `p` is measurable at
time `p`. -/
theorem stronglyMeasurable_freshCharacter_filtration {S : Finset ℕ} {p : ℕ}
    (hS : ∀ q ∈ S, q ≤ p) :
    StronglyMeasurable[εFiltration p]
      (fun omega : Omega => freshCharacter omega S) := by
  classical
  unfold freshCharacter
  exact Finset.stronglyMeasurable_fun_prod S fun q hq =>
    stronglyMeasurable_ε_filtration (hS q hq)

theorem stronglyMeasurable_freshCharacter (S : Finset ℕ) :
    StronglyMeasurable (fun omega : Omega => freshCharacter omega S) := by
  classical
  unfold freshCharacter
  exact Finset.stronglyMeasurable_fun_prod S fun q _ =>
    (measurable_ε q).stronglyMeasurable

@[simp] theorem abs_freshCharacter (omega : Omega) (S : Finset ℕ) :
    |freshCharacter omega S| = 1 := by
  rw [freshCharacter, Finset.abs_prod]
  simp

theorem integrable_freshCharacter (S : Finset ℕ) :
    Integrable (fun omega : Omega => freshCharacter omega S) μ := by
  apply Integrable.of_bound (stronglyMeasurable_freshCharacter S).aestronglyMeasurable 1
  exact ae_of_all μ fun omega => by simp [Real.norm_eq_abs]

/-- The smooth sum at cutoff `p` only depends on coordinates at most `p`. -/
theorem stronglyMeasurable_Ψ_filtration (z p : ℕ) :
    StronglyMeasurable[εFiltration p] (fun omega : Omega => Ψ omega z p) := by
  classical
  simp_rw [Ψ_eq_sum_squarefreeSmoothSets]
  apply Finset.stronglyMeasurable_fun_sum
  intro S hS
  apply stronglyMeasurable_freshCharacter_filtration
  intro q hq
  have hsub := (mem_squarefreeSmoothSets.mp hS).1 hq
  exact Nat.le_of_lt_succ (Nat.mem_primesBelow.mp hsub).1

theorem stronglyAdapted_Ψ (z : ℕ) :
    StronglyAdapted εFiltration (fun p omega => Ψ omega z p) :=
  fun p => stronglyMeasurable_Ψ_filtration z p

theorem integrable_Ψ (z p : ℕ) :
    Integrable (fun omega : Omega => Ψ omega z p) μ := by
  classical
  simp_rw [Ψ_eq_sum_squarefreeSmoothSets]
  exact integrable_finset_sum _ fun S _ => integrable_freshCharacter S

/-- A deterministic finite bound on every smooth sum. -/
theorem norm_Ψ_le_card (omega : Omega) (z p : ℕ) :
    ‖Ψ omega z p‖ ≤ (squarefreeSmoothSets z p).card := by
  rw [Ψ_eq_sum_squarefreeSmoothSets]
  calc
    ‖∑ S ∈ squarefreeSmoothSets z p, freshCharacter omega S‖ ≤
        ∑ S ∈ squarefreeSmoothSets z p, ‖freshCharacter omega S‖ :=
      norm_sum_le _ _
    _ = (squarefreeSmoothSets z p).card := by
      simp [Real.norm_eq_abs]

/-- In particular every time slice is in `L²`. -/
theorem memLp_two_Ψ (z p : ℕ) :
    MemLp (fun omega : Omega => Ψ omega z p) 2 μ := by
  apply MemLp.of_bound (p := (2 : ℝ≥0∞)) (μ := μ)
    ((stronglyMeasurable_Ψ_filtration z p).mono
      (εFiltration.le p)).aestronglyMeasurable
    ((squarefreeSmoothSets z p).card : ℝ)
  exact ae_of_all μ fun omega => norm_Ψ_le_card omega z p

/-- A future sign has conditional expectation zero with respect to the current
natural filtration. -/
theorem condExp_ε_succ_eq_zero (p : ℕ) :
    μ[fun omega : Omega => ε omega (p + 1) | εFiltration p] =ᵐ[μ]
      (0 : Omega → ℝ) := by
  have h := iIndepFun_ε.condExp_natural_ae_eq_of_lt
    stronglyMeasurable_εProcess p.lt_succ_self
  simpa [εFiltration, εProcess, integral_ε] using h

/-- The one-step martingale identity. -/
theorem condExp_Ψ_succ (z p : ℕ) :
    μ[fun omega : Omega => Ψ omega z (p + 1) | εFiltration p] =ᵐ[μ]
      fun omega => Ψ omega z p := by
  by_cases hp : (p + 1).Prime
  · let c : Omega → ℝ := fun omega => Ψ omega (z / (p + 1)) p
    have hc_meas : StronglyMeasurable[εFiltration p] c :=
      stronglyMeasurable_Ψ_filtration _ _
    have hc_int : Integrable c μ := integrable_Ψ _ _
    have heps_int : Integrable (fun omega : Omega => ε omega (p + 1)) μ :=
      integrable_ε _
    have hprod_int : Integrable
        (fun omega : Omega => c omega * ε omega (p + 1)) μ := by
      apply hc_int.mul_bdd (c := 1)
        (measurable_ε (p + 1)).aestronglyMeasurable
      exact ae_of_all μ fun omega => by simp [Real.norm_eq_abs]
    have hpull :
        μ[fun omega : Omega => c omega * ε omega (p + 1) | εFiltration p] =ᵐ[μ]
          fun omega => c omega *
            (μ[fun omega : Omega => ε omega (p + 1) | εFiltration p]) omega :=
      condExp_mul_of_stronglyMeasurable_left hc_meas hprod_int heps_int
    have hinczero :
        μ[fun omega : Omega => ε omega (p + 1) * c omega | εFiltration p] =ᵐ[μ]
          (0 : Omega → ℝ) := by
      calc
        μ[fun omega : Omega => ε omega (p + 1) * c omega | εFiltration p]
            =ᵐ[μ]
            μ[fun omega : Omega => c omega * ε omega (p + 1) | εFiltration p] :=
          condExp_congr_ae (ae_of_all μ fun omega => mul_comm _ _)
        _ =ᵐ[μ] fun omega => c omega *
            (μ[fun omega : Omega => ε omega (p + 1) | εFiltration p]) omega := hpull
        _ =ᵐ[μ] 0 := by
          filter_upwards [condExp_ε_succ_eq_zero p] with omega homega
          simp [homega]
    have hrec : (fun omega : Omega => Ψ omega z (p + 1)) =
        (fun omega => Ψ omega z p) +
          (fun omega => ε omega (p + 1) * c omega) := by
      funext omega
      simpa [c, hp] using Ψ_recurrence omega z (Nat.succ_pos p)
    rw [hrec]
    have hbase :
        μ[fun omega : Omega => Ψ omega z p | εFiltration p] =ᵐ[μ]
          fun omega => Ψ omega z p := by
      rw [condExp_of_stronglyMeasurable (εFiltration.le p)
        (stronglyMeasurable_Ψ_filtration z p) (integrable_Ψ z p)]
    exact (condExp_add (integrable_Ψ z p)
      ((integrable_congr (ae_of_all μ fun omega => mul_comm _ _)).mpr hprod_int)
      (εFiltration p)).trans
      (by simpa only [Pi.add_apply, Pi.zero_apply, add_zero] using hbase.add hinczero)
  · have hrec : (fun omega : Omega => Ψ omega z (p + 1)) =
        fun omega => Ψ omega z p := by
      funext omega
      simpa [hp] using Ψ_recurrence omega z (Nat.succ_pos p)
    rw [hrec]
    rw [condExp_of_stronglyMeasurable (εFiltration.le p)
      (stronglyMeasurable_Ψ_filtration z p) (integrable_Ψ z p)]

/-- The concrete smooth-prime process is a square-integrable martingale. -/
theorem martingale_Ψ (z : ℕ) :
    Martingale (fun p omega => Ψ omega z p) εFiltration μ := by
  apply martingale_nat (stronglyAdapted_Ψ z) (integrable_Ψ z)
  intro p
  exact (condExp_Ψ_succ z p).symm

end Problem520
end Erdos
