import Mathlib.Analysis.SpecificLimits.Normed
import Mathlib.Probability.ConditionalExpectation

open Filter MeasureTheory
open scoped Topology

namespace Erdos
namespace Problem520

/-- Abstract data occurring in the thin-prime-block estimate.

For a block index `ell` and a prime-block index `j`, `U ell j` is the maximal
energy `U_j`, `I ell j` is the normalized Euler-product energy `I_j`, and
`filtration ell j` represents the sigma-algebra generated by signs up to the
end of block `j`.
-/
structure ThinBlockData (Ω : Type*) [MeasurableSpace Ω] where
  /-- Number of prime blocks at scale `ell`. -/
  J : ℕ → ℕ
  /-- Prime-block filtration at scale `ell`. -/
  filtration : ℕ → ℕ → MeasurableSpace Ω
  filtration_le : ∀ ell j, filtration ell j ≤ ‹MeasurableSpace Ω›
  /-- Maximal smooth energy in block `j`. -/
  U : ℕ → ℕ → Ω → ℝ
  /-- Normalized Euler-product energy. -/
  I : ℕ → ℕ → Ω → ℝ

/-- The exact Lean interface for the new estimate (16).

The assertion is an almost-everywhere conditional inequality.  Integrability
is included explicitly so that conditional expectation cannot silently fall
back to its nonintegrable default value.  This proposition is the main new
probability/analysis obligation; it is not postulated as an axiom.
-/
def ThinPrimeBlockMomentBound {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) (d : ThinBlockData Ω) : Prop :=
  ∃ C : ℝ, 0 < C ∧
    (∀ ell j omega, 0 ≤ d.U ell j omega) ∧
    ∀ ell : ℕ, 1 ≤ ell →
      ∀ j : ℕ, 1 ≤ j → j ≤ d.J ell →
        ∀ r : ℕ, 2 ≤ r →
          Integrable (fun omega => d.U ell j omega ^ r) μ ∧
          ∀ᵐ omega ∂μ,
            (μ[(fun omega => d.U ell j omega ^ r) |
                d.filtration ell (j - 1)] omega) ^ (1 / (r : ℝ))
              ≤ C * Real.exp (C * r / ell) * d.I ell (j - 1) omega

/-- Polynomially many blocks can be union-bounded against a `2^{-ell}` tail.

This is the summability calculation used after taking `r = ell` in (16).
-/
theorem summable_polynomial_mul_two_pow (K : ℕ) :
    Summable (fun ell : ℕ =>
      (ell : ℝ) ^ K * (1 / 2 : ℝ) ^ ell) := by
  exact summable_pow_mul_geometric_of_norm_lt_one K (by norm_num)

/-- A constant multiple of the polynomial/geometric block budget is still
summable. -/
theorem summable_const_mul_polynomial_mul_two_pow (C : ℝ) (K : ℕ) :
    Summable (fun ell : ℕ =>
      C * ((ell : ℝ) ^ K * (1 / 2 : ℝ) ^ ell)) :=
  (summable_polynomial_mul_two_pow K).mul_left C

end Problem520
end Erdos
